### ISSUE TITLE
minipage beschreiben?

### ISSUE THREAD

**Issue by pgundlach** [texdoc/l2kurz#1]
Wir könnten uns überlegen, ob wir die Umgebung minipage beschreiben sollen.

**Comment by braichle** [comment]
Die Diskussion, ob man eine Installationsanleitung zur "l2kurz" hinzufügt, kommt immer mal wieder auf.

Das Problem einer solchen ist aber besser in einer separaten Anleitung aufgehoben, da sich die "l2kurz" nicht so häufig geändert hat oder ändern wird, wie eine Installationsanleitung für eine bestimmte TeX-Verteilung (TeX Live, MikTeX, welche Version, welcher Editor/Umgebung etc.?) und Betriebssystem (welches Windows, welches Linux etc.?).

Bin also eher für eine "l2inst_kurz" o.ä. :-)

**Comment by pgundlach** [comment]
@braichle Dies hier ist über die Minipage, nicht über die Installation, oder habe ich was übersehen?

Ansonsten: ich schließe mal das Ticket, weil l2kurz derzeit ein "totes" Dokument ist, und sowieso mal überarbeitet werden könnte und müsste.
