### ISSUE TITLE
hyperref toc

### ISSUE THREAD

**Issue by muhbian** [texdoc/l2kurz#4]
Moin,

wäre klasse, wenn beim \usepackage{hyperref} noch die Option 'linktoc=all' hinzugefügt werden könnte. Hilft bestimmt Vielen! 
Danke und Gruß!

**Comment by pgundlach** [comment]
Fixed with 4ceeabc00402b848939cc521c962cb477d3dceb5 - somehow this issue wasn't closed yet. Thanks.
